### ISSUE TITLE
Erreur sur valeur transmise à home assistant

### ISSUE THREAD

**Issue by McRMX** [NicolasBernaerts/tasmota#12]
Bonjour, 

Je viens tout juste d'installer votre version de Tasmota [tasmota-teleinfo.bin.gz] sur un D1mini.
Je recupere mes infos.

![Capture d’écran 2023-05-31 à 12 32 42](https://github.com/NicolasBernaerts/tasmota/assets/54727223/f69b0079-a465-44a6-8e13-6e08671d055e)

Seulement de façon assez aléatoire je récupère une valeur erroné dans la journée.  (environ 9000 kWh).

Ayant ajouter la variable "energy today" dans la panneaux "Energy" de Home Assistant, le graph s'adapte à la valeur la plus grande et la courbe n'est plus bonne.

Avez vous déjà rencontré ce problème ?

![image](https://github.com/NicolasBernaerts/tasmota/assets/54727223/e97969a1-d1a7-48f7-a78d-a0d270d23530)
![image](https://github.com/NicolasBernaerts/tasmota/assets/54727223/8dd4a225-602a-4997-a684-c19167d594e6)![image](https://github.com/NicolasBernaerts/tasmota/assets/54727223/07b68e60-fcbc-47f8-b23b-945ebc0c52ca)

**Comment by NicolasBernaerts** [comment]
Bonsoir @McRMX,
Je viens de déposer une nouvelle version basée sur Tasmota 12.5.0.
Pourriez-vous vérifier que le problème persiste avec cette version ?

**Comment by McRMX** [comment]
Je test et reviens vers vous.
Petite remarque : ce lien ne fonctionne pas ou plus.
These projects are explained in detail under http://www.bernaerts-nicolas.fr/iot/

**Comment by NicolasBernaerts** [comment]
Hello,
Les graphs sont interessants à 2 niveaux :

 - 382 messages : c'est le nombre de messages reçus depuis le boot. c'est très faible. est-ce que votre tasmota ne reboot pas à cause d'une alimentation un peu faible ?
 
 - pics à 9000kWh entre 9h et 11h totalement plat ... est ce que vous envoyez vraiment la bonne donnée ?

Pour avoir la puissance instantanée en Wh, il faut activer l'option METER, clé W1 :
 2:44:40.456 MQT: turenne/compteur/tele/SENSOR = {"Time":"2023-06-01T22:44:40","METER":{"PH":1,"ISUB":45,"PSUB":9000,"PMAX":9000,"U1":232,"P1":1238,"W1":965,"I1":5.0,"C1":0.78}}

Pour récupérer le total en kWh, il faut activer l'option "TIC" et repérer la clé servie par votre compteur.

**Comment by McRMX** [comment]
En effet il semblerait que Energy today reparte régulièrement de 0. Un reboot ferait cela ?
Je vais changé l'alimentation pour m'assurer de ça.

Les infos envoyé a Home assistant sont ajouté a l'aide d'un add-on ( https://www.home-assistant.io/integrations/tasmota)
Il récupère toutes les infos en théories.
![Capture d’écran 2023-06-01 à 23 43 31](https://github.com/NicolasBernaerts/tasmota/assets/54727223/ab8a1fd5-1dcd-4521-a898-6caca23419cb)

Concernant la configuration, j'ai effectivement pas tout compris. J'ai cherché un peu de doc mais j'ai pas trouvé.(d'ou l'indication d'un lien HS qui correspondait peut être a des infos supplémentaires).

Apres votre dernier message j'ai changé les paramètres comme ceci.
![Capture d’écran 2023-06-01 à 23 40 44](https://github.com/NicolasBernaerts/tasmota/assets/54727223/44547048-7722-488e-8632-459af1c2c4fa)

**Comment by NicolasBernaerts** [comment]
Hello,
D'après le site du plugin, il doit s'appuyer sur les messages ENERGY

tele/SENSOR = {"Time":"2023-06-02T07:03:16","ENERGY":{"TotalStartTime":"2023-02-24T23:45:20","Total":26305.301,"Yesterday":16.881,"Today":4.221,"Period":0,"Power":500,"ApparentPower":625,"ReactivePower":375,"Factor":0.81,"Voltage":234,"Current":2.671},

Vous pouvez donc configurer "Message Data" sur "None" car ENERGY est publié en standard.

Vérifiez en mode console que ENERGY soit publié régulièrement et que la valeur "Power" soit cohérente.
Si c'est le cas, le problème doit venir du traitement fait par le plugin Home Assistant.

N'utilisant pas Home Assistant mais OpenHab, j'aurais du mal à vous aider sur ce sujet.

**Comment by McRMX** [comment]
La valeur power est coherente. 
![Capture d’écran 2023-06-02 à 11 20 14](https://github.com/NicolasBernaerts/tasmota/assets/54727223/85c8cda5-d1da-46e2-9ce2-f7e882a0aacf)

Effectivement "Messages / Cos Phi" la valeur Message repasse régulièrement a zero. --> Et du coup le Energy Today est remis a zero également.
![Capture d’écran 2023-06-02 à 08 33 56](https://github.com/NicolasBernaerts/tasmota/assets/54727223/c26d7528-236f-43c4-81fb-ef0c83139762)

D'ou j'imagine l'erreur de calcul. 

J'imagine qu'elle devrait le faire seulement a minuit. Qu'est ce qui pourrait produire ça ?

**Comment by NicolasBernaerts** [comment]
Le plus courant est une faiblesse de l'alimentation. Cela provoque des reboots intempestifs. Votre courbe de puissance montre des parties sans données. Il faudrait chercher dans ce sens.

**Comment by McRMX** [comment]
Je n'ai pas compris votre 1er phrase, sans doute une erreur de frappe.
J'ai changé toutes l'alimentation sur le D1mini Cable / chargeur, j'ai également remplacé le D1mini. Ce qui explique les interruptions. Les coupures correspondent au different test que j'ai fait.
Hier soir tard 00h30 et ce matin après 9h.

Je n'y touche pas ce soir pour voir la différence avec la courbe que je vous ai envoyé.
y a t'il un moyen de savoir le nombre de reboot / un log un peu plus bavard ?

Je vois quelques fois apparaitre une ligne rebott / erreur qui ne s'affiche pas tout le temps.

**Comment by NicolasBernaerts** [comment]
Ces éléments sont dans "Information"

**Bout count** présente le nombre total de reboot depuis le début
**Restart Reason** indique la cause du reboot (**Software/System restart** signale par exemple un redémarrage à la demande de l'utilisateur)

**Comment by NicolasBernaerts** [comment]
Je viens de publier une version 11.1 où le compteur **Energy today** est sauvegardé entre les reboot.
Cela devrait aider à régler le problème des incohérences d'historique.

**Comment by McRMX** [comment]
J'ai pas eu trop le temps aujourd'hui d'y jeter un coup d'oeil.

J'ai pu voir tout de meme bcp de reboot.
![Capture d’écran 2023-06-03 à 19 03 42](https://github.com/NicolasBernaerts/tasmota/assets/54727223/5799799c-cd7d-4ec8-bd2d-da7d93349ca0)

Merci pour la modif. Je test rapidement

**Comment by NicolasBernaerts** [comment]
Cela ressemble a un problème connu pour les cartes WeMos non originales.
https://www.letscontrolit.com/forum/viewtopic.php?t=6720

**Comment by McRMX** [comment]
J'ai pu mettre la dernière MAJ 11.1.

J'ai eu bon espoir ce matin avec 1000 messages affich, l'energy today semblait cohérente.

Mais quelques minutes plus tard sans doute après un reboot.(J'ai reset le compteur "bount count" et ce matin je suis déja a 27 sans doute comme vous l'avez dit avec une carte WeMos non originales). 
![Capture d’écran 2023-06-04 à 10 13 15](https://github.com/NicolasBernaerts/tasmota/assets/54727223/4b71e9f8-3b7c-4a2e-966b-d1e02e7d5f02)
Il semblerait qu'il n'y ai plus d'erreur sur le calcul, mais la valeur energy today repasse a zero.

Il arrive quelques fois que mon Active power soit à zero (Panneaux solaire) pourrait t'il y avoir une erreur de calcul a ce moment la ?

Ou trouve t'on un D1mini ou ESP32 officiel (J'avoue être un peu perdu avec ces modèles de cartes).

**Comment by NicolasBernaerts** [comment]
Bonjour,

La valeur Energy Today en enregistrée en cas de reboot planifié, de mise à jour, ... mais pas en cas de reboot intempestif.
