### ISSUE TITLE
gazpar wiring schematics

### ISSUE THREAD

**Issue by albebert** [NicolasBernaerts/tasmota#14]
HI, can you add some schematics of gazpar wiring please ?

**Comment by NicolasBernaerts** [comment]
Gazpar fournit un contact sec.
Voici un exemple de PCB pour Wemos.
Le connecteur Gazpar est noté Haut et Bas.

![Capture d’écran du 2024-01-25 09-31-15](https://github.com/NicolasBernaerts/tasmota/assets/7038880/936180cb-fe67-462f-a02e-753dd06ff134)

**Comment by albebert** [comment]
merci pour le schéma !
