### ISSUE TITLE
Cannot Find LD2410TX/RX in TASMOTA Configuration

### ISSUE THREAD

**Issue by 86TRUENO** [NicolasBernaerts/tasmota#19]
I'm using TASMOTA 13.3 and added the extension for LD2450. It responds when typing "ld2450_help" in the console. However, LD2410 cannot be found in this page.
![image](https://github.com/NicolasBernaerts/tasmota/assets/59081867/c4e7b5e3-91f3-43f1-adcb-ce228b959e78)

**Comment by NicolasBernaerts** [comment]
You have to compile your build with LD2410 module also.

**Comment by 86TRUENO** [comment]
thx! Problems solved
