### ISSUE TITLE
"Energie active injectée totale" EAIT

### ISSUE THREAD

**Issue by Yourry** [NicolasBernaerts/tasmota#26]
Bonjour à tous,
Je viens tout juste faire le changement de TIC en historique vers standard (sous contrat tempo) car j'ai quelques panneaux solaires et je voulais savoir si mon installation rivalise avec une centrale nucléaire :)
Je pensais récupérer la valeur de suproduction, genre "Energie active injectée totale EAIT" mais à priori non.
N'étant pas un expert, est-ce qu'il y a un truc à faire, car dans les messages reçu j'ai :
![image](https://github.com/NicolasBernaerts/tasmota/assets/5098104/e4227766-ad71-42c8-a8e7-534f30fff3f8)

Il n'y a pas d'erreur de trame d'après le menu principale. Un truc à cocher/renseigner ?
Pour info ma demande d'autoconso a été faite officilement. 
@++

**Comment by NicolasBernaerts** [comment]
Votre compteur ne génère pas l'étiquette EAIT. Le problème est donc chez votre fournisseur d'accès qui n'a pas finalisé sa configuration.
Quand l'étiquette apparaîtra, une section production devrait apparaître automatiquement sur la page d'accueil.

**Comment by Yourry** [comment]
C'est noté, je verais avec EDF alors pour leur demander une mise à jour de la TIC.
Merci pour votre réponse.

**Comment by Yourry** [comment]
Merci pour l'aide.
