### ISSUE TITLE
Teleinfo today repart à zéro plusieurs fois par jour

### ISSUE THREAD

**Issue by sj29fr** [NicolasBernaerts/tasmota#30]
Bonjour @NicolasBernaerts,
j'ai flashé le dernier tasmota-teleinfo-4m2m.bin sur un wemos d1 mini.
Mon compteur est un Linky monophasé en 12KVA.
Je rencontre un problème avec le compteur de conso journalisé.
Dans HA, sensor conso_aujourdhui repart à 0 plusieurs fois par jour sans explication.
Est-ce qu'il vaudrait mieux utiliser le firmware de base tasmota-teleinfo.bin peut être plus stable ?
Mon besoin est juste de remonter les infos en MQTT vers HA. Je n'ai pas besoin de stocker d'historique.
Je rajoute des screenshots pour montrer l'incohérence entre le total journalier web et le total journalier MQTT.
Cordialement,
Sébastien

**Comment by sj29fr** [comment]
![Screenshot_20240426_130802_Home Assistant](https://github.com/NicolasBernaerts/tasmota/assets/79538834/b6969873-e653-4ed2-8a12-039d85d35d49)
![Screenshot_20240426_130747_Home Assistant](https://github.com/NicolasBernaerts/tasmota/assets/79538834/2f4ed03d-e28f-442d-9970-ce93c7da10d5)
![Screenshot_20240426_130724_Samsung Internet](https://github.com/NicolasBernaerts/tasmota/assets/79538834/57611a0e-c91d-477a-9858-a056cf16f6d0)

**Comment by sj29fr** [comment]
En fait, MQTT export "Consommation Aujourd'hui = 38Wh" au lieu de "Energie aujourd'hui 13.358kWh"
Est-ce possible de modifier l'export MQTT ?
A quoi correspond du coup "Consommation Aujourd'hui" car ça me parait faible ?
Et pourquoi repart t-il à 0 pendant la période de 24h ?

**Comment by NicolasBernaerts** [comment]
A minuit Conso hier est initialisé à conso aujourd'hui et conso aujourd'hui initialisé à zéro. On parle ici d'un total quotidien en Wh. 
Dans le mqtt,  CONSO.TDAY doit augmenter tout au long de la journée comme conso aujourd'hui. Si elle repasse à zéro dans la journée c'est qu'il y a un problème ... sans doute des redémarrage intempestif de l'ESP sans sauvegarde du compteur.
Pour TeleInfo, je conseille fortement un esp32 car l'esp8266 est tres limité en mémoire et cela peut être la cause de plantages s'il est trop sollicité.
Si vous préférez utiliser la clé du total ENERGY c'est tout a fait possible mais elle est sans doute beaucoup moins précise car issue d'un calcul tasmota et non pas des totaux du linky.
Pour ma part, je n'utilise jamais les données ENERGY, je me contente de les alimenter.

**Comment by NicolasBernaerts** [comment]
Pour info, s'il n'y a pas eu de reboot programmé, 1082 trames à 13:06 signifie clairement un reboot intempestif.

**Comment by sj29fr** [comment]
Merci pour ces infos.
J'ai un esp32 de côté. Je vais modifier ma carte pour voir si c'est plus stable

**Comment by sj29fr** [comment]
Merci pour ces infos.
J'ai un esp32 de côté. Je vais modifier ma carte pour voir si c'est plus stable

**Comment by NicolasBernaerts** [comment]
![Screenshot_20240426-212250](https://github.com/NicolasBernaerts/tasmota/assets/7038880/36773704-1e4d-410f-9ae9-8100202d8cdd)

Voici mon TeleInfo esp8266 en cours d'utilisation. Aucun reboot depuis la dernière mise a jour il y a plus de 4 jours.

**Comment by sj29fr** [comment]
Je confirme qu'avec un ESP32, le firmware est OK.
Je vais peut être prendre un ESP32-C3 mini, ça sera plus pratique à intégrer dans mon tableau.
