### ISSUE TITLE
3 phase problem

### ISSUE THREAD

**Issue by reguiny** [NicolasBernaerts/tasmota#33]
J'utilise Teleinfo et lorsque le courant utilisé est inférieur à 1 ampère, l'écran affiche les trois phases avec la même valeur.

I am using teleinfo and when the current used is below 1 amp the display shows all three phases as the same value.
![ Teleinfo - Menu principal](https://github.com/NicolasBernaerts/tasmota/assets/98203573/d25689e7-fd73-45fc-8748-da94596a8cad)

**Comment by NicolasBernaerts** [comment]
Hello,
Votre compteur est en mode historique.
Il ne transmet donc pas la puissance par phase mais :
- une puissance globale
- un courant par phase arrondi à l'ampère (sans aucune décimale)

Avec 133 VA, logiquement le compteur doit transmettre 0 A sur chaque phase (à vérifier via le menu Messages).
Dans ce cas, nous n'avons donc aucun moyen de savoir quelle phase consomme. 
D'où la répartition arbitraire entre les 3 phases de la puissance globale annoncée.

**Comment by reguiny** [comment]
Merci, je vais changer le compteur au standard.
