### ISSUE TITLE
Reboot en boucle

### ISSUE THREAD

**Issue by Lutty76** [NicolasBernaerts/tasmota#35]
Bonjour,

Mon esp 8266 reboot en boucle dès que je le branche à mon compteur. 

Avant, j'utilisais ce [firmware](https://github.com/Jason2866/Tasmota-specials/tree/firmware/firmware/tasmota/other) sans souci (en version Tasmota 12.1.1.2 by Theo Arends).

Donc mes branchements sont corrects.

J'utilise ce [circuit](https://github.com/hallard/WeMos-TIC) comme interface entre mon ESP8266 et mon compteur Linky.

Je suis en monophasé sans contrat particulier.
J'ai des panneaux solaires qui parfois produisent plus que je consomme (courant injecté dans les réseaux, mais sans revente).

Je suis sur le format standard

Voici un exemple d'info remonté par mon ancien firmware :

```
{"ADSC":"031864908464","VTIC":2,"NGTF":"      BASE      ","LTARF":"      BASE      ","EAST":22377879,"EASF01":22377879,"EASF02":0,"EASF03":0,"EASF04":0,"EASF05":0,"EASF06":0,"EASF07":0,"EASF08":0,"EASF09":0,"EASF10":0,"EASD01":7256061,"EASD02":5557560,"EASD03":2470254,"EASD04":7094004,"IRMS1":3,"URMS1":236,"PREF":6,"PCOUP":6,"SINSTS":642,"SMAXSN":2519,"SMAXSN-1":3328,"UMOY1":235,"STGE":"003AC001","PRM":2147483647,"RELAIS":0,"NTARF":1,"NJOURF":0,"NJOURF+1":0}
```

J'ai activé le "EnergyConfig Full"  peut-être y aura-t-il plus d'info : 

```
12:54:58.670 MQT: teleinfo/tele/teleinfo/SENSOR = {"TIC":{"ADSC":"031864908464","VTIC":2,"NGTF":"      BASE      ","LTARF":"      BASE      ","EAST":23938478,"EASF01":23938478,"EASF02":0,"EASF03":0,"EASF04":0,"EASF05":0,"EASF06":0,"EASF07":0,"EASF08":0,"EASF10":0,"EASD01":7530338,"EASD02":6208960,"EASD03":2643980,"EASD04":7555200,"IRMS1":3,"URMS1":240,"PREF":6,"PCOUP":6,"SINSTS":723,"SMAXSN":2525,"SMAXSN-1":2964,"UMOY1":240,"STGE":"003A4001","PRM":2147483647,"RELAIS":0,"NTARF":1,"NJOURF":0,"NJOURF+1":0,"EASF09":0}}
```

Je n'ai pas pu me brancher en série sur le compteur, il faut que je regarde comment faire ça.

Merci

**Comment by NicolasBernaerts** [comment]
Bonjour,
La dernière version publiée sur Github fonctionne parfaitement avec un ESP32 mais pose problème sur un ESP8266.
Je pense avoir trouvé la source du problème (différence de comportement sur PSTR () entre ESP32 et ESP8266.
Je devrais pouvoir publier un nouveau binaire avec le correctif d'ici 1 ou 2 jours.
Quelle version de ROM utilisez-vous (1Mb, 4Mb ou 16Mb) ?

**Comment by Lutty76** [comment]
Bonjour,

J'ai essayé la 1M et la 4M, normalement la board est compatible 4M (WeMos D1 Mini)

**Comment by NicolasBernaerts** [comment]
En fait j'ai fait pas mal d'évolutions alors que mon ESP de test est un ESP32. En vérifiant, certaines évolutions sont trop lourdes pour un ESP8266 en terme de RAM.
Je vais faire une version light compatible ESP8266.

**Comment by NicolasBernaerts** [comment]
Je viens de publier une version ESP8266 qui devrait corriger le problème.
Est-ce ok ?

**Comment by Lutty76** [comment]
Désolé je n'ai pas pris le temps de regarder ça (et je n'ai pas les notif de réponse sur l'issue), je regarde ça dans la soirée, Merci !

**Comment by NicolasBernaerts** [comment]
Toutes les valeurs sont à zéro, la page Configuration / TeleInfo nécessite sans doute une verification.

**Comment by Lutty76** [comment]
Pourtant je réutilise celle de mon firmware d'avant basé sur tasmota qui fonctionne correctement, je vais étudier ça quand même

**Comment by Lutty76** [comment]
Je suis passé sur un ESP32 pour ne plus etre limité niveau performance. Je n'ai aps approfondi pour l'ESP8266, mais ça a fonctionné directement avec l'ESP32. J'espère que c'était juste un soucis de configuration.

**Comment by NicolasBernaerts** [comment]
Ticket fermé faute d'éléments.
