### ISSUE TITLE
Linky Triphasée PH2=PH3

### ISSUE THREAD

**Issue by CTPA** [NicolasBernaerts/tasmota#38]
Bonjour et merci pour le travail Nicolas,

J'ai installé sur une carte Olimex ESP32-POE, le firmware "tasmota32-teleinfo.bin" en version 14.8 Beta.
J'ai un compteur Linky 3 phases en mode historique (demande pour le mode standard faite hier). 

Petit bug report : la Ph2 et Ph3 sont identiques en U / I / W / VA

<img width="233" alt="image" src="https://github.com/user-attachments/assets/a64604c1-cf0c-4501-91db-408c5c87ce9a">

Cordialement

**Comment by NicolasBernaerts** [comment]
Hello,
En mode historique le courant est publié en A sans aucune décimale. Cela signifie qu'il n'y a aucune précision.
Le problème vient sans doute de là.
Regardez dans le menu "Message" pour voir si les courants des phases 2 et 3 ne sont pas à 1A.
Cela expliquerait la similitude entre les 2 phases.
En passant en mode standard, la précision par phase n'est pas du tout la même.

**Comment by CTPA** [comment]
Bonjour, effectivement en regardant de plus prêt cela n'arrive que quand les valeurs sont basse.
Je vais attendre sagement la TIC en mode standard :-)

Merci pour la réponse

**Comment by NicolasBernaerts** [comment]
Avant que vous ne passiez en mode standard je serai très intéressé si vous pouviez enregistrer 5 ou 10 mn de flux teleinfo. En effet je n'ai aucun jeu de données triphasé mode historique pour mes tests de non regression. Merci d'avance.

**Comment by CTPA** [comment]
Avec plaisir,
Pouvez vous me préciser le format/méthode.
Pensez vous au messages dans la console, avec le format suivant : 

22:56:58.004 MQT: Compteur_Maison_Linky/tele/TIC = {"Time":"2024-09-09T22:56:57","TIC":{"ADCO":"031876067693","OPTARIF":"BBR(","ISOUSC":"30","BBRHCJB":"050664130","BBRHPJB":"044197790","BBRHCJW":"002332363","BBRHPJW":"000978604","BBRHCJR":"000632297","BBRHPJR":"000317331","PTEC":"HCJB","DEMAIN":"----","IINST1":"013","IINST2":"014","IINST3":"011","IMAX1":"060","IMAX2":"060","IMAX3":"060","PMAX":"20947","PAPP":"08940","HHPHC":"A","MOTDETAT":"000000","PPOT":"00"}}

22:57:00.007 MQT: Compteur_Maison_Linky/tele/SENSOR = {"Time":"2024-09-09T22:56:59","METER":{"PH":3,"ISUB":30,"PSUB":6000,"PMAX":6000,"U1":230,"I1":13.28,"P1":3055,"W1":3018,"C1":0.98,"U2":230,"I2":14.30,"P2":3290,"W2":3250,"C2":0.98,"U3":230,"I3":11.23,"P3":2585,"W3":2553,"C3":0.98,"U":230,"I":38.82,"P":8930,"W":8821,"C":0.98,"YDAY":42602,"TDAY":25335},"CONTRACT":{"serial":31876067693,"name":"Tempo","period":"Creuses Bleu","color":"Bleu","hour":"Creuse","CONSO":99122522,"HCJB":50664137,"HPJB":44197790,"HCJW":2332363,"HPJW":978604,"HCJR":632297,"HPJR":317331},"CAL":{"level":1,"hp":0},"RELAY":{"R1":0,"R2":0,"R3":0,"R4":0,"R5":0,"R6":0,"R7":0,"R8":0},"ALERT":{"Load":0,"Volt":0,"Preavis":0,"Label":""}}

**Comment by CTPA** [comment]
Ce n'est pas le cas dans le .txt en PJ mais comme vous pouvez le voir ci dessous, quand je branche 1 ou 2 VE  j'arrive a avoir un cos phi ~=0, ce qui donne du coup des puissances nulles :-)

![Capture d’écran 2024-09-08 223938](https://github.com/user-attachments/assets/4e29f14e-60d0-406d-ad0f-14592fe6d07d)

![Capture d’écran 2024-09-08 224019](https://github.com/user-attachments/assets/62ba410b-0eb1-452d-87c2-d36a18cddae7)

[20240909_10MinFluxTIC.txt](https://github.com/user-attachments/files/16936688/20240909_10MinFluxTIC.txt)

**Comment by NicolasBernaerts** [comment]
C'est étonnant car dans les logs le cosphi est toujours supérieur à 0.75.
Pour l'enregistrement, il faudrait démarrer le serveur TCP et enregistrer les flux directement depuis le port TCP ouvert. La procédure est décrite dans la section concernant le serveur TCP.
Avec cet enregistrement je pourrais essayer de reproduire le problème de cosphi.
Merci

**Comment by CTPA** [comment]
Les logs transmis n'ont pas été fait en même temps que les graphs. C'est des impressions écran que j'ai fait plus tôt.

Je n'ai pas de PC sous linux, j'ai tenté l'opération avec nmap sous windows, mais je dois mal m'y prendre car je n'y arrive pas.
Avez vous une solution avec un PC windows?

**Comment by NicolasBernaerts** [comment]
Vous devriez pouvoir le faire avec putty
https://documentation.help/PuTTY/using-rawprot.html
En activant le logging, le flux devrait être enregistré en live.
A tester ...

**Comment by CTPA** [comment]
Pas de soucis pour le tcp_start avec le # de port.
Dans Putty, j'ai mis l'IP, le port et la connexion en RAW.
Et essayé toutes les différentes options de loggin session, mais cela ne semble pas fonctionner correctement.

![image](https://github.com/user-attachments/assets/df3ba202-5493-47ce-bc40-163096990ae7)

**Comment by localhost61** [comment]
Essayez plutôt avec  [Curl pour Windows](https://curl.se/windows/).
-> [mon post](https://community.ch2i.eu/post/5217) sur le site de Charles Hallard

**Comment by NicolasBernaerts** [comment]
Merci pour le tip !
Étant sous linux depuis plus de 10 ans, je deviens un handicapé de windows :-(

**Comment by CTPA** [comment]
Merci.
Malheureusement, je n'ais pas eu plus de chance...

cmd => curl ip:port
>curl: (1) Received HTTP/0.9 when not allowed

cmd => curl --http0.9 ip:port
> Warning: Binary output can mess up your terminal. Use "--output -" to tell curl to output it to your terminal anyway,
Warning: or consider "--output <FILE>" to save to a file.

cmd => curl --http0.9 --output toto.txt ip:port
> $  (    !`@*H	 !!~ EC(4!  8%	 
>   )  = $  	  -!R     4 PA$% $! $!$!    % 2	  (    -$    
>   !@ P@H !!~ E$
>  
>  
>  
>   @   5 		 ; 1 (- @@  t @)  @ @
>   @!%   % ! %$ (    -$      !@ P@H !!~ E
>  ( 
>   )    - !	  =!Q   5 4$ (P@$%$`$!$$!$)    % 2	  (    -$      !@ P@H !!~ E
>   ( 
>   % $    -  !P 9   5  P)@!     	%!! $ % ) %$ (   -$  (4  
>   !1(@=@pH !!~ E$A! 
> (
>    )  3      
> 1 % $  )  )-$  ! P)P  !!~ E4 
>  
>  
>    (@
>    % !!$
>  % A%-"A  P @) @	 @  @!%@$ % ! %$    -$  @  % !`RPH	 !!~ EC % 0 '$  9% A
>   e=  
>    -!! 
> !!0$ A %!2$  1P @  @+ @+  @!   %$!( !%   $!   !      P)P5 !!~ E$ 
>  '(! 
>  
>   e=     ,	  &4   AP @) @ @)  @!  % %$ % $   @  	,5 I   !  !$` E4 
>  
> (8 
>  -  a  
>    -!)	!! $ 	a$%2    T @  @+ 
> @
>   @!%  %$!  !     (@ $    !1@=@pH !!~ E +  
>    
>  -  @= $  	  	  $ @- @@ 0 P @	  @ @  @!$ % ! %$ (  ( -$      !@ P@H !!~ E 
>  (! 
>  
>   e=  
>    -!!
> !!0$ 
> A %!2$  ET @  @) @  @!%   % ) !$ (   -$  @ 
>  !@ P@H !!~ E$A! 
> (
>  -  a  
>    (  	(%P ,@4   	  `$!$ $!$)  @ % 	     -$   @ 
>  !@ P@H !!~ E$ 
>  ()$, 9 
>   e=  
>    	!  	(%Q %,@$   P @) @ @  @!%   % ) !$    -$   @   !`P@H )!~ E$%! 
>    
> 
>  -  a  0  	 (%Q%,B4 (  P @) @	 @
>   @!%   % ! %$    -$   @  % !`P@H )~ M$<!  H8
>  -  a  
>    
> !! 	  @Q  %%"  P @) @	 @  @!%  	 !$! P !4 $! 1 ($  $  % !(`H	 !!~ EC(4! ' (-	$  9- 
>   m       
> 	  -!P   5   At @  @ @)  @!$    !!  1  $    !(@XPH	 !!~ MC 0! ' 8-	$  9- 
>   @    
>   66 I) @aAa)Q4 J $  $!$!$)  4 % 1&	   $ ),  %
> (% !(@5XH !!~ MB<! '$  9 =  a  
> H !!~ EC(4! ' 
>   % $   = 
>   	!q  9 A4  () !  1       @!%   %$!( !   % (  $    !(@#H	 !!~ MC  0 '	P 
>  
>   @ 5 $  -  	  @)) @@ %-  `$!$$! $)    % 2	  (   -$   @   !@P@ !!~ E$	! (! 
>  
>   e=  
>    -!! (4!I$H(@ 4  ( ET @  @) 
> @  @!%   % ) !$    -$   @   !@P@H )!~ E$ 
>  (!$% 9 
>   @  3!  9P  @r  aAQ)B!  !$ $!$!$)    % 2	     -$   @   !`R@H )!~ E$ 
>  (!$% 9 
>   @  3!
>   9P  @p  aAQ	PP) ) 1   	!!!%   % ! %$    -$   @  % !`P@H )~ E4 
>  (!$%	 
>   @  3!  9P  @p  aAQ)PQ) )    	!!!%   % ! %$   ( - !$ % % !`PPH !!~ E$%	 !  
>  
>   a  
> H !!~ EC(4! ' (%	$! 9=   @  ;!	  =!P    5 P) @!   ! %    @! $ ! ! %$   ( ),  %  % !(`H	 !!~ E< 
>   
>    
>   ;   !
>  	 	$0$ A$!2   At @)  @ @+  @! $ P !    ( $  $ %4  p)P  !!~ E, 
>   
>      ;  
>   	 	$
> E$% !  
>   5 $    
>   	!y  @q   	  ) !     	%!! $ ! ! % 	   ( -$  F %
>  !`PPH	 !!~ MC  ! '$! 9%   @    
>   	!y  @q  4`4    $!$`$!$ $! $  % 2&    ( -$   % % !`PPH	 !!~ E  
> 0 '$! 9% 
>   @    
>   	!y  @q  04$)( ) !   1     @! $ ! ! % 	   ( -$  % % !`PPH	 !!~ E,
>   '(! 

**Comment by localhost61** [comment]
@CTPA, on est bien d'accord :

- Que vous avez d'abord démarré le serveur sur votre carte Olimex avec :
>`tcp_start 8888`
- Que la commande a été acceptée
- Que sous Windows, dans une boîte DOS vous avez simplement tapé
 >`curl IP:Port`
 où `IP` est l'adresse IP de votre carte Olimex et `Port` est l'argument de la commande `tcp_start`, soit 8888 dans mon exemple ce qui donne par exemple: `curl 192.168.1.10:8888`

**Comment by CTPA** [comment]
Oui précisément.

**Comment by NicolasBernaerts** [comment]
Il semble que nc / netcat soit disponible sous windows 
https://nmap.org/download.html#windows

**Comment by CTPA** [comment]
J'aurai vraiment essayé mais à mon retour de wkd le compteur été en mode standard. 

Par curiosité j'ai refait la manipulation et elle semble avoir fonctionné, peut être un bug du coup, voici 4-5 secondes de résultat : 

> CCASN	E240924223000	03720	@
> CCASN-1	E240924220000	00716	]
> UMOY1	E240924225000	237	5
> UMOY2	E240924225000	239	8
> UMOY3	E240924225000	241	2
> STGE	013A0000	:
> MSG1	PAS DE          MESSAGE         	<
> PRM	21198552806784	C
> RELAIS	001	C
> NTARF	01	N
> NJOURF	00	&
> NJOURF+1	00	B
> PJOURF+1	00004001 06004002 22004001 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE	.
> 
> ADSC	031876067693	E
> VTIC	02	J
> DATE	E240924225642		H
> NGTF	     TEMPO      	F
> LTARF	    HC  BLEU    	^
> EAST	099765794	G
> EASF01	051134735	?
> EASF02	044370464	C
> EASF03	002332363	:
> EASF04	000978604	G
> EASF05	000632297	C
> EASF06	000317331	9
> EASF07	000000000	(
> EASF08	000000000	)
> EASF09	000000000	*
> EASF10	000000000	"
> EASD01	038701095	A
> EASD02	034316976	H
> EASD03	015398300	?
> EASD04	011349423	>
> IRMS1	007	5
> IRMS2	005	4
> IRMS3	005	5
> URMS1	239	H
> URMS2	241	B
> URMS3	242	D
> PREF	18	H
> PCOUP	18	"
> SINSTS	03834	X
> SINSTS1	01557	I
> SINSTS2	01185	G
> SINSTS3	01092	E
> SMAXSN	E240924022201	05125	3
> SMAXSN1	E240924082102	01910	(
> SMAXSN2	E240924185705	02772	=
> SMAXSN3	E240924022200	03077	)
> SMAXSN-1	E240923012353	11673	\
> SMAXSN1-1	E240923012345	03571	L
> SMAXSN2-1	E240923012349	04544	R
> SMAXSN3-1	E240923014754	04651	T
> CCASN	E240924223000	03720	@
> CCASN-1	E240924220000	00716	]
> UMOY1	E240924225000	237	5
> UMOY2	E240924225000	239	8
> UMOY3	E240924225000	241	2
> STGE	013A0000	:
> MSG1	PAS DE          MESSAGE         	<
> PRM	21198552806784	C
> RELAIS	001	C
> NTARF	01	N
> NJOURF	00	&
> NJOURF+1	00	B
> PJOURF+1	00004001 06004002 22004001 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE	.
> 
> ADSC	031876067693	E
> VTIC	02	J
> DATE	E240924225643		I
> NGTF	     TEMPO      	F
> LTARF	    HC  BLEU    	^
> EAST	099765795	H
> EASF01	051134736	@
> EASF02	044370464	C
> EASF03	002332363	:
> EASF04	000978604	G
> EASF05	000632297	C
> EASF06	000317331	9
> EASF07	000000000	(
> EASF08	000000000	)
> EASF09	000000000	*
> EASF10	000000000	"
> EASD01	038701096	B
> EASD02	034316976	H
> EASD03	015398300	?
> EASD04	011349423	>
> IRMS1	006	4
> IRMS2	005	4
> IRMS3	005	5
> URMS1	239	H
> URMS2	241	B
> URMS3	242	D
> PREF	18	H
> PCOUP	18	"
> SINSTS	03827	Z
> SINSTS1	01552	D
> SINSTS2	01183	E
> SINSTS3	01092	E
> SMAXSN	E240924022201	05125	3
> SMAXSN1	E240924082102	01910	(
> SMAXSN2	E240924185705	02772	=
> SMAXSN3	E240924022200	03077	)
> SMAXSN-1	E240923012353	11673	\
> SMAXSN1-1	E240923012345	03571	L
> SMAXSN2-1	E240923012349	04544	R
> SMAXSN3-1	E240923014754	04651	T
> CCASN	E240924223000	03720	@
> CCASN-1	E240924220000	00716	]
> UMOY1	E240924225000	237	5
> UMOY2	E240924225000	239	8
> UMOY3	E240924225000	241	2
> STGE	013A0000	:
> MSG1	PAS DE          MESSAGE         	<
> PRM	21198552806784	C
> RELAIS	001	C
> NTARF	01	N
> NJOURF	00	&
> NJOURF+1	00	B
> PJOURF+1	00004001 06004002 22004001 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE	.
> 
> ADSC	031876067693	E
> VTIC	02	J
> DATE	E240924225645		K
> NGTF	     TEMPO      	F
> LTARF	    HC  BLEU    	^
> EAST	099765797	J
> EASF01	051134738	B
> EASF02	044370464	C
> EASF03	002332363	:
> EASF04	000978604	G
> EASF05	000632297	C
> EASF06	000317331	9
> EASF07	000000000	(
> EASF08	000000000	)
> EASF09	000000000	*
> EASF10	000000000	"
> EASD01	038701098	D
> EASD02	034316976	H
> EASD03	015398300	?
> EASD04	011349423	>
> IRMS1	007	5
> IRMS2	005	4
> IRMS3	005	5
> URMS1	239	H
> URMS2	241	B
> URMS3	242	D
> PREF	18	H
> PCOUP	18	"
> SINSTS	03836	Z
> SINSTS1	01558	J
> SINSTS2	01185	G
> SINSTS3	01093	F
> SMAXSN	E240924022201	05125	3
> SMAXSN1	E240924082102	01910	(
> SMAXN2	E240924185705	02772	=
> SMAXSN3	E240924022200	03077	)
> SMAXSN-1	E240923012353	11673	\
> SMAXSN1-1	E240923012345	03571	L
> SMAXSN2-1	E240923012349	04544	R
> SMAXSN3-1	E240923014754	04651	T
> CCASN	E240924223000	03720	@
> CCASN-1	E240924220000	00716	]
> UMOY1	E240924225000	237	5
> UMOY2	E240924225000	239	8
> UMOY3	E240924225000	241	2
> STGE	013A0000	:
> MSG1	PAS DE          MESSAGE         	<
> PRM	21198552806784	C
> RELAIS	001	C
> NTARF	01	N
> NJOURF	00	&
> NJOURF+1	00	B
> PJOURF+1	00004001 06004002 22004001 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE	.
> 
> ADSC	031876067693	E
> VTIC	02	J
> DATE	E240924225646		L
> NGTF	     TEMPO      	F
> LTARF	    HC  BLEU    	^
> EAST	099765798	K
> EASF01	051134739	C
> EASF02	044370464	C
> EASF03	002332363	:
> EASF04	000978604	G
> EASF05	000632297	C
> EASF06	000317331	9
> EASF07	000000000	(
> EASF08	000000000	)
> EASF09	000000000	*
> EASF10	000000000	"
> EASD01	038701099	E
> EASD02	034316976	H
> EASD03	015398300	?
> EASD04	011349423	>
> IRMS1	006	4
> IRMS2	005	4
> IRMS3	005	5
> URMS1	239	H
> URMS2	241	B
> URMS3	242	D
> PREF	18	H
> PCOUP	18	"
> SINSTS	03828	[
> SINSTS1	01551	C
> SINSTS2	01185	G
> SINSTS3	01092	E
> SMAXSN	E240924022201	05125	3
> SMAXSN1	E240924082102	01910	(
> SMAXSN2	E240924185705	02772	=
> SMAXSN3	E240924022200	03077	)
> SMAXSN-1	E240923012353	11673	\
> SMAXSN1-1	E240923012345	03571	L
> SMAXSN2-1	E240923012349	04544	R
> SMAXSN3-1	E240923014754	04651	T
> CCASN	E240924223000	03720	@
> CCASN-1	E240924220000	00716	]
> UMOY1	E240924225000	237	5
> UMOY2	E240924225000	239	8
> UMOY3	E240924225000	241	2
> STGE	013A0000	:
> MSG1	PAS DE          MESSAGE         	<
> PRM	21198552806784	C
> RELAIS	001	C
> NTARF	01	N
> NJOURF	00	&
> NJOURF+1	00	B
> PJOURF+1	00004001 06004002 22004001 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE	.
> 
> ADSC	031876067693	E
> VTIC	02	J
> DATE	E240924225647		M
> NGTF	     TEMPO      	F
> LTARF	    HC  BLEU    	^
> EAST	099765799	L
> EASF01	051134740	;
> EASF02	044370464	C
> EASF03	002332363	:
> EASF04	000978604	G
> EASF05	000632297	C
> EASF06	000317331	9
> EASF07	000000000	(
> EASF08	000000000	)
> EASF09	000000000	*
> EASF10	000000000	"
> EASD01	038701100	4
> EASD02	034316976	H
> EASD03	015398300	?
> EASD04	011349423	>
> IRMS1	006	4
> IRMS2	005	4
> IRMS3	005	5
> URMS1	239	H
> URMS2	241	B
> URMS3	242	D
> PREF	18	H
> PCOUP	18	"
> SINSTS	03831	U
> SINSTS1	01553	E
> SINSTS2	01186	H
> SINSTS3	01092	E
> SMAXSN	E240924022201	05125	3
> SMAXSN1	E240924082102	01910	(
> SMAXSN2	E240924185705	02772	=
> SMAXSN3	E240924022200	03077	)
> SMAXSN-1	E240923012353	11673	\
> SMAXSN1-1	E240923012345	03571	L
> SMAXSN2-1	E240923012349	04544	R
> SMAXSN3-1	E240923014754	04651	T
> CCASN	E240924223000	03720	@
> CCASN-1	E240924220000	00716	]
> UMOY1	E240924225000	237	5
> UMOY2	E240924225000	239	8
> UMOY3	E240924225000	241	2
> STGE	013A0000	:
> MSG1	PAS DE          MESSAGE         	<
> PRM	21198552806784	C
> RELAIS	001	C
> NTARF	01	N
> NJOURF	00	&
> NJOURF+1	00	B
> PJOURF+1	00004001 06004002 22004001 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE	.
> 
> ADSC	031876067693	E
> VTIC	02	J
> DATE	E240924225648		N
> NGTF	     TEMPO      	F
> LTARF	    HC  BLEU    	^
> EAST	099765800	;
> EASF01	051134741	<
> EASF02	044370464	C
> EASF03	002332363	:
> EASF04	000978604	G
> EASF05	000632297	C
> EASF06	000317331	9
> EASF07	000000000	(
> EASF08	000000000	)
> EASF09	000000000	*
> EASF10	000000000	"
> EASD01	038701101	5
> EASD02	034316976	H
> EASD03	015398300	?
> EASD04	011349423	>
> IRMS1	007	5
> IRMS2	005	4
> IRMS3	005	5
> URMS1	239	H
> URMS2	241	B
> URMS3	242	D
> PREF	18	H
> PCOUP	18	"
> SINSTS	03849	^
> SINSTS1	01572	F
> SINSTS2	01185	G
> SINSTS3	01092	E
> SMAXSN	E240924022201	05125	3
> SMAXSN1	E240924082102	01910	(
> SMAXSN2	E240924185705	02772	=
> SMAXSN3	E240924022200	03077	)
> SMAXSN-1	E240923012353	11673	\
> SMAXSN1-1	E240923012345	03571	L
> SMAXSN2-1	E240923012349	04544	R
>

**Comment by CTPA** [comment]
curl --http0.9 --output toto.txt ip:port
