### ISSUE TITLE
Homeassistant dashboard energy - Données de consommation "retournée" apparemment erronées

### ISSUE THREAD

**Issue by perefouras** [NicolasBernaerts/tasmota#41]
Bonjour,

J'utilise depuis une semaine sur un Denky votre firmware qui est venu remplacer avantageusement (!) l'original teleinfo.
Tout fonctionne correctement mais dans le dashboard Energie de HomeAssistant je n'arrive à expliquer le "total retourné" qui apparait chaque jour sur le graphe pour la période minuit/1 heure :

<img width="496" alt="image" src="https://github.com/user-attachments/assets/2a4270ae-c47a-4daf-ab6c-a34a26147781">

Je précise que j'ai un kit solaire plug&play en production mais en autoconsommation (pas de revente au réseau)
La timezone est bien configurée sur tasmota (GMT+2 en ce moment) et sur Homeassistant (Paris).
J'ai installé la beta16 qui ne change rien.

Auriez-vous une idée ?
Merci.

**Comment by NicolasBernaerts** [comment]
Vous utilisez sans doute le total quotidien METER/TDAY au lieu du total general CONTRACT/CONSO.
Le total quotidien revenant à 0 à minuit, vous avez cette différence.
Utilisez CONTRACT/CONSO cela devrait être mieux.

**Comment by perefouras** [comment]
En effet, merci.  J'étais allé l'explication un peut trop loin !
