### ISSUE TITLE
Compatibilité avec compteur divisionnaire

### ISSUE THREAD

**Issue by sinclairfr** [NicolasBernaerts/tasmota#43]
Bonjour Nicolas,

Tout d'abord bravo et merci pour votre excellent travail sur ce projet ! 
Je n'ai pas de linky, mais un compteur divisionnaire à l'ancienne de type "divisionnaire" avec télétransmission.
Exemple : [https://voltebox.com/collections/compteurs-electriques/products/zcd126](url)

Je me demandais s'il y avait une moyen de faire fonctionner l'extension avec ce type de protocole de données ? 

En vous remerciant par avance,
M.

**Comment by NicolasBernaerts** [comment]
Bonsoir sinclairfr,
Parlez vous de ce compteur ?
https://www.polier.fr/_files/ugd/511b90_df1b5c3ef93d4da2b5bbd6ead161261e.pdf

**Comment by sinclairfr** [comment]
Merci pour la réponse !
Oui en effet, tous les compteurs avec la téléinfo ancienne version.
Je me demandais si le protocole linky était le même.

**Comment by NicolasBernaerts** [comment]
Hello,
Bonne nouvelle !
Ces compteurs utilisent le protocole TeleInfo historique qui devrait être parfaitement géré par mon firmware. 
Vous devez simplement configurer la vitesse à 1200 bps et tout devrait être reconnu.
Quel contrat avec vous ?

**Comment by sinclairfr** [comment]
J'utilise ce module :
![image](https://github.com/user-attachments/assets/c53188d6-899c-4a91-b709-8cc8df00df43)
et la configuration suivante:
![Capture d'écran 2024-10-05 104734](https://github.com/user-attachments/assets/78ff9094-9165-4593-80ba-2991afe58b55)
![Capture d'écran 2024-10-05 104934](https://github.com/user-attachments/assets/f934d532-f8c7-466a-b9ea-2aa9a8473cbe)
Mon contrat est un EDF Zen Online avec HP/HC.

**Comment by sinclairfr** [comment]
Je suis en train de me demande si tout bêtement le pin-out n'est peut être pas le bon dans la configuration Wemos Teleinfo.

**Comment by sinclairfr** [comment]
Problème réglé, j'avais le mauvais GPIO. Pour information, gpio 37 = teleinfo RX sur ce modèle, on ne sait jamais, cela peut aider quelqu'un d'autre.
Merci en tout cas !

**Comment by NicolasBernaerts** [comment]
Bonjour Medhi,
Très bonne nouvelle.
Concernant les options cochées, je vous conseille de décocher :
- données temps réel
- données Teleinfo brutes
Elles ne sont d'aucune utilisée pour Home assistant.
Ayant un contrat historique, vous pouvez décocher les données "Relai virtuel".
L'option "A chaque message reçu" est dans la plupart des cas inutiles.
Si vous cochez "Tous les 100 VA", vous aurez le même résultat et votre ESP sera beaucoup moins stressé.
Pour Home Assistant, aucun besoin de "Energie Tasmota".
