### ISSUE TITLE
Teleinfo  et passage de ESPhome à Tasmota

### ISSUE THREAD

**Issue by aladin2000** [NicolasBernaerts/tasmota#45]
Bonjour Nicolas
je viens de parcourir rapidement ta contribution, je te remercie tout d'abord pour tout cela....

je rencontre des probleme de taille de code sur mon ESP-01 1M
car je fais des display sur un mini ecran 128x64  en plus du code teleinfo.
`
display:
 - platform: ssd1306_i2c
    model: "SSD1306 128x64"
     ....
   id: ha_display
    pages:
      - id: page1
        lambda: |-
          it.fill(black);
          it.rectangle(0,  0, it.get_width(), it.get_height(), blue);
          it.rectangle(0, 18, it.get_width(), it.get_height(), blue);   // header bar
          it.printf(1 , 5, id(font3), white, TextAlign::LEFT, "%d", id(linky_status).state);
          it.print(it.get_width() / 2, 11, id(font3), red, TextAlign::CENTER, "TiC");
          it.strftime(it.get_width() - 18 , 10, id(font3), red, TextAlign::CENTER, "%H:%M", id(my_time).now());
          it.printf(it.get_width() / 2 ,  40, id(font2), white, TextAlign::CENTER, "%05.0f va", id(consommation).state);
      - id: page2
        lambda: |-
          it.rectangle(0,  0, it.get_width(), it.get_height(), blue);
          it.rectangle(0, 18, it.get_width(), it.get_height(), blue);   // header bar
          it.print(it.get_width() / 2, 11, id(font3), red, TextAlign::CENTER, "TIC");
          it.printf(1 , 5, id(font3), white, TextAlign::LEFT, "%d", id(linky_status).state);
          it.strftime(it.get_width() - 18 , 10, id(font3), red, TextAlign::CENTER, "%H:%M", id(my_time).now());
          it.print(0, 20, id(font3), white, TextAlign::LEFT, "P1:");
          it.print(0, 32, id(font3), white, TextAlign::LEFT, "P2:");
          it.print(0, 44, id(font3), white, TextAlign::LEFT, "P3:");
          it.printf(it.get_width() - 38, 20, id(font3), white, TextAlign::RIGHT, "%05.0f", id(consomp1).state);
          it.printf(it.get_width() - 38, 32, id(font3), white, TextAlign::RIGHT, "%05.0f", id(consomp2).state);
          it.printf(it.get_width() - 38, 44, id(font3), white, TextAlign::RIGHT, "%05.0f", id(consomp3).state);
          it.printf(it.get_width() - 11, 20, id(font3), white, TextAlign::RIGHT, "va");
          it.printf(it.get_width() - 11, 32, id(font3), white, TextAlign::RIGHT, "va");
          it.printf(it.get_width() - 11, 44, id(font3), white, TextAlign::RIGHT, "va");
....

`
En fait avant de basculer vers ta solution  je voulais connaitre ton point de vue sur la facilité de faire la meme chose en tasmota.... pour ajouter les feature support ecran....

Merci par avance de ton avis éclairé. sur ce code : 

// Configuration de l'affichage SSD1306 dans Tasmota
// Assurez-vous que l'affichage est correctement connecté et configuré dans Tasmota
// Utilisez les commandes suivantes dans la console Tasmota

// Configuration de l'affichage
I2CScan             // Pour vérifier si l'écran est détecté à l'adresse correcte (0x3C)
DisplayModel 2      // Modèle pour SSD1306

// Afficher les informations sur l'écran
DisplayText "TiC"   // Affiche le texte "TiC" au centre de l'écran
DisplayText "P1:"   // Affiche le texte "P1:"
DisplayText "P2:"   // Affiche le texte "P2:"
DisplayText "P3:"   // Affiche le texte "P3:"

// Pour afficher les valeurs des capteurs (par exemple consommation)
DisplayText "Consommation P1: [consomp1]"   // Remplacez [consomp1] par la valeur réelle
DisplayText "Consommation P2: [consomp2]"   // Remplacez [consomp2] par la valeur réelle
DisplayText "Consommation P3: [consomp3]"   // Remplacez [consomp3] par la valeur réelle

// Pour afficher l'heure et le statut Linky
DisplayText "[linky_status]"                 // Remplacez [linky_status] par la valeur réelle

**Comment by NicolasBernaerts** [comment]
Bonjour, 
Aucune idée car je n'utilise pas d'écran.
Mais l'ESP 8266 étant déjà stressé niveau RAM par la réception TeleInfo en mode standard, la sagesse serait de basculer sur un ESP32 qui possède beaucoup plus de RAM.

**Comment by NicolasBernaerts** [comment]
En allant regarder dans Tasmota, la gestion des écrans avec le nouveau driver universel nécessite l'utilisation de Berry ... donc d'un ESP32.

**Comment by NicolasBernaerts** [comment]
Ticket fermé car déjà réglé via Berry.
