### ISSUE TITLE
Denky D4 & InfluxBD integation

### ISSUE THREAD

**Issue by Spike91000** [NicolasBernaerts/tasmota#47]
Bonjour

 

Je viens de flasher un Denky D4 v1.3 avec le firmware [tasmota32-teleinfo-denkyd4.factory.bin v14.8 & souhaiterais importer les relevés dans une instance INFLUXDB.

Cependant l'integration INFLUXDB n'est plus disponible 
![image](https://github.com/user-attachments/assets/7274dc52-c895-43f7-a31b-c89a6265c5bf)

Débutant en domotique avec le flashing des ESP, ai-je utilisé la bonne version du firmware  ou cette option n'est elle plus intégré ? 

Cordialement

**Comment by NicolasBernaerts** [comment]
Bonjour Spike,
La version avec intégration InfluxDB est actuellement en test.
Je ne l'ai pas encore publiée mais j'ai commencé à mettre à jour la documentation.
La version étant plutôt stable, je vais publier la version Denky D4 qui l'intègre.
Ce sera la v14.9beta9.

**Comment by NicolasBernaerts** [comment]
Le binary DenkyD4 est publié.

**Comment by Spike91000** [comment]
Merci Bcp
Je le testerai ce week-end
