### ISSUE TITLE
[error] Please install gen_esp32part.py

### ISSUE THREAD

**Issue by t-e-d-d-y** [NicolasBernaerts/tasmota#8]
Bonjour, je tente de flasher un esp32 avec `tasmota-flash` mais j'obtiens l'erreur suivante : `[error] Please install gen_esp32part.py`, je dois rater quelque chose, mais je ne vois pas comment installer gen_esp32part.py.

Merci d'avance

**Comment by NicolasBernaerts** [comment]
Tool gen_esp32part.py was needed for ESP32 partitioning.
With new .factory.bin firmware it is not needed anymore.
I uploaded a new version of tasmota-flash that uses these new images for initial flash.
It should work OOTB.
