### ISSUE TITLE
No Daily/Weekly/Monthly graphs

### ISSUE THREAD

**Issue by NlsMyFox** [NicolasBernaerts/tasmota#9]
Bonjour @NicolasBernaerts et avant tout, bravo pour ce superbe travail.

J'utilise la dernière version des binaire téléinfo (10.2) avec un ESP-01s et dans la partie graphes je n'ai que le Live et plus les graphes Daily/Weekly/Monthly que j'avais sur le version 9.0.

Cela vient-il du fait que je sois sur ESP-01 sans LittleFS ?

Merci pour votre réponse.

**Comment by NicolasBernaerts** [comment]
Bonjour Nicolas,
Effectivement, sur la dernière version j'ai ajouté les compteurs annuels et revu la façon de gérer les graphiques.
Sachant que toutes les données sont perdues à chaque redémarrage, je n'ai gardé que le live pour les données hors LittleFS.
Les graphs Daily, weekly et les compteurs mensuels et annuels n'apparaissent maintenant que si l'ESP dispose des fichiers correspondants sur la partition LittleFS. L'idéal est de disposer d'un ESP 4M ou mieux encore 16M.

**Comment by NlsMyFox** [comment]
Bonjour et mille mercis pour tout.

C'est très clair.
